query ShipmentsByCarrier($carrier: String) {
  shipmentsByCarrier(carrier: $carrier) {
    id
    trackingNumber
    carrier
    delivered
    orderId
    invoiceId
    externalLink
    createdIn
    lastInteractionDate
  }
}
